import numpy as np
from ase import Atoms

def format_vector(label, v):
    return f"{label}: {v[0]:12.4f} {v[1]:12.4f} {v[2]:12.4f}\n"

def format_atom(prefix, atom, phase_map=None, vib_default="dr3 0.025 0.025 0.025"):
    symbol = atom.symbol
    label = phase_map.get(symbol, symbol) if phase_map else symbol
    pos = atom.position
    return f"{prefix}: {label:<6s} {pos[0]:10.4f} {pos[1]:10.4f} {pos[2]:10.4f} {vib_default}\n"

def write_bul(filename, bulk_atoms: Atoms, phase_map=None):
    """
    Writes the CLEED .bul file.
    """
    cell = bulk_atoms.get_cell()
    
    with open(filename, 'w') as f:
        f.write(f"c: Generated by cleed-convert from {bulk_atoms.get_chemical_formula()}\n")
        f.write("# Lattice Vectors\n")
        f.write(format_vector("a1", cell[0]))
        f.write(format_vector("a2", cell[1]))
        f.write(format_vector("a3", cell[2]))
        
        f.write("# Bulk Atoms\n")
        for atom in bulk_atoms:
            f.write(format_atom("pb", atom, phase_map))
            
        # Add standard params if missing (users should edit these)
        f.write("\n# Standard Parameters (Adjust as needed)\n")
        f.write("vr: -10.0\n")
        f.write("vi: 4.0\n")

def write_inp(filename, overlayer_atoms: Atoms, bulk_atoms: Atoms, phase_map=None):
    """
    Writes the CLEED .inp file.
    """
    cell = bulk_atoms.get_cell() # Overlayer uses bulk 2D periodicity usually
    
    with open(filename, 'w') as f:
        f.write(f"c: Generated by cleed-convert\n")
        
        # Write Superstructure Matrix (Identity for now)
        f.write("# Superstructure (Assuming 1x1 relative to defined Bulk)\n")
        f.write("m1: 1.0 0.0\n")
        f.write("m2: 0.0 1.0\n")
        
        f.write("# Overlayer Atoms\n")
        for atom in overlayer_atoms:
            f.write(format_atom("po", atom, phase_map))
            
        f.write("\n# Search Parameters\n")
        f.write("ei: 50.0\n")
        f.write("ef: 400.0\n")
        f.write("es: 2.0\n")
