name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
sort-direction: ascending

categories:
  - title: "Breaking changes"
    labels:
      - "breaking"
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "Maintenance"
    labels:
      - "chore"
      - "ci"
      - "build"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "bug"
      - "fix"
  default: patch

template: |
  ## Summary
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

