exclude_paths:
  # Generated/build artifacts (some are currently committed historically)
  - "build/**"
  - "CMakeFiles/**"
  - "src/**/CMakeFiles/**"
  - "doc/_build/**"
  - "Dockerfile"

  # Tests (still checked locally via pre-commit/cppcheck)
  - "tests/**"

  # Vendored third-party code
  - "src/contrib/**"

  # Legacy program entrypoint (large, historical main() - keep functional but
  # avoid failing Codacy on complexity/LOC limits).
  - "src/mkiv/mkiv.c"

  # IDE/user configuration files
  - "**/*.pro.user"
  - ".externalToolBuilders/**"
  - ".cproject"
  - ".project"

  # Binaries and object files (should not be analysed)
  - "**/*.exe"
  - "**/*.o"
  - "**/*.a"
  - "**/*.so"
  - "**/*.dylib"
  - "**/*.dll"
