# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Oct 09 12:11:15 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/office-chart-line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 311, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.imageSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setObjectName(_fromUtf8("imageSlider"))
        self.verticalLayout.addWidget(self.imageSlider)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuExtract = QtGui.QMenu(self.menubar)
        self.menuExtract.setObjectName(_fromUtf8("menuExtract"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/document-open-8.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/application-exit-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/document-save-as-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionCopy = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit-copy-6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionAbout_Extract_pyV = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/help-about-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Extract_pyV.setIcon(icon5)
        self.actionAbout_Extract_pyV.setObjectName(_fromUtf8("actionAbout_Extract_pyV"))
        self.actionRename = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit-rename.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename.setIcon(icon6)
        self.actionRename.setObjectName(_fromUtf8("actionRename"))
        self.actionConvert = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-refresh-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert.setIcon(icon7)
        self.actionConvert.setObjectName(_fromUtf8("actionConvert"))
        self.actionExtract = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/archive-extract-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract.setIcon(icon8)
        self.actionExtract.setObjectName(_fromUtf8("actionExtract"))
        self.actionExtraction_Help = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/help-contents-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtraction_Help.setIcon(icon9)
        self.actionExtraction_Help.setObjectName(_fromUtf8("actionExtraction_Help"))
        self.actionAdd_Mask = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/user-info-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Mask.setIcon(icon10)
        self.actionAdd_Mask.setObjectName(_fromUtf8("actionAdd_Mask"))
        self.actionCopy_Raw_Image = QtGui.QAction(MainWindow)
        self.actionCopy_Raw_Image.setObjectName(_fromUtf8("actionCopy_Raw_Image"))
        self.actionMark_as_Reference = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/format-text-direction-ltr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMark_as_Reference.setIcon(icon11)
        self.actionMark_as_Reference.setObjectName(_fromUtf8("actionMark_as_Reference"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionExtraction_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Extract_pyV)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCopy_Raw_Image)
        self.menuExtract.addAction(self.actionRename)
        self.menuExtract.addAction(self.actionConvert)
        self.menuExtract.addSeparator()
        self.menuExtract.addAction(self.actionAdd_Mask)
        self.menuExtract.addAction(self.actionMark_as_Reference)
        self.menuExtract.addSeparator()
        self.menuExtract.addAction(self.actionExtract)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuExtract.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Extract-PyV", None))
        self.label.setText(_translate("MainWindow", "Image", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuExtract.setTitle(_translate("MainWindow", "Process", None))
        self.actionOpen.setText(_translate("MainWindow", "Import...", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionAbout_Extract_pyV.setText(_translate("MainWindow", "About Extract-PyV", None))
        self.actionRename.setText(_translate("MainWindow", "Rename...", None))
        self.actionRename.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionConvert.setText(_translate("MainWindow", "Convert...", None))
        self.actionExtract.setText(_translate("MainWindow", "Extract...", None))
        self.actionExtract.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionExtraction_Help.setText(_translate("MainWindow", "Help...", None))
        self.actionExtraction_Help.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionAdd_Mask.setText(_translate("MainWindow", "Add Mask", None))
        self.actionAdd_Mask.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionCopy_Raw_Image.setText(_translate("MainWindow", "Copy (Raw)", None))
        self.actionMark_as_Reference.setText(_translate("MainWindow", "Mark As Reference", None))
        self.actionMark_as_Reference.setShortcut(_translate("MainWindow", "Ctrl+1", None))

import res_rc
