# -*- coding: utf-8 -*-
#
# CLEED documentation build configuration file, created by
# sphinx-quickstart on Fri Jun 06 15:22:54 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.graphviz',
    'sphinx.ext.todo',
    # API documentation from Doxygen
    'breathe',
    # NOTE: exhale removed due to extremely slow builds (40+ min) and
    # compatibility issues with C codebases. Use Breathe directives directly.
    # Scientific documentation
    'sphinxcontrib.bibtex',
    'sphinxcontrib.mermaid',
    # Usability
    'sphinx_copybutton',
]

# -- Todo Extension Configuration ------------------------------------------
# Show TODOs in output (useful for tracking documentation work)
todo_include_todos = False  # Set to True to show TODO items in output

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'CLEED'
copyright = u'2014, Georg Held, Liam Deacon & collaborators'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1.0-dev'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Breathe Configuration ------------------------------------------------
# Integration with Doxygen-generated XML documentation

breathe_projects = {
    "CLEED": "_build/doxygen/xml"
}
breathe_default_project = "CLEED"

# Show function parameters in API docs
breathe_default_members = ('members', 'undoc-members')


# -- BibTeX Configuration -------------------------------------------------
# Scientific references and citations

bibtex_bibfiles = ['references.bib']
bibtex_default_style = 'unsrt'
bibtex_reference_style = 'label'  # Use citation keys as labels to avoid duplicates


# -- Mermaid Configuration ------------------------------------------------
# Diagrams and flowcharts

mermaid_version = "10.6.1"
mermaid_init_js = "mermaid.initialize({startOnLoad:true, theme:'neutral'});"


# -- Graphviz Configuration -----------------------------------------------
# For call graphs and other diagrams

graphviz_output_format = 'svg'


# -- Suppress Warnings Configuration --------------------------------------
# Suppress specific warnings that are expected and not actionable

suppress_warnings = [
    # Duplicate C++ declarations from Breathe (C types appearing in C++ domain)
    'duplicate_declaration.cpp',
    # Unreferenced footnotes in manual (OCR transcription artifacts)
    'ref.footnote',
    # Duplicate bibtex labels (same author/year in different contexts)
    'bibtex.duplicate_label',
]


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "CLEED"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "CLEED_logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "CLEED_logo.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
smartquotes = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'CLEEDdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'CLEED.tex', u'CLEED Documentation',
   u'Georg Held, Liam Deacon \\& collaborators', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = "CLEED_logo.png"

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
latex_show_urls = 'no'

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'cleed', u'CLEED Documentation',
     [u'Georg Held, Liam Deacon & collaborators'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'CLEED', u'CLEED Documentation',
   u'Georg Held, Liam Deacon & collaborators', 'CLEED', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'CLEED'
epub_author = u'Georg Held, Liam Deacon & collaborators'
epub_publisher = u'Georg Held, Liam Deacon & collaborators'
epub_copyright = u'2014, Georg Held, Liam Deacon & collaborators'

# The basename for the epub file. It defaults to the project name.
#epub_basename = u'CLEED'

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}


# -- Nitpick Configuration ------------------------------------------------
# Ignore warnings about missing references for C standard library types
# and project-specific macros that Doxygen doesn't document

nitpick_ignore = [
    # C standard library types
    ("cpp:identifier", "size_t"),
    ("cpp:identifier", "uint64_t"),
    ("cpp:identifier", "uint32_t"),
    ("cpp:identifier", "int64_t"),
    ("cpp:identifier", "int32_t"),
    ("cpp:identifier", "FILE"),
    ("cpp:identifier", "va_list"),
    ("cpp:identifier", "u_short"),
    ("cpp:identifier", "FILETIME"),
    # Project-specific types (documented in different headers/as typedefs)
    ("cpp:identifier", "lattice_t"),
    ("cpp:identifier", "atom_t"),
    ("cpp:identifier", "coord_t"),
    ("cpp:identifier", "miller_hkl_t"),
    ("cpp:identifier", "real"),
    ("cpp:identifier", "sr_optimizer_run_fn"),
    ("cpp:identifier", "sratom_str"),
    ("cpp:identifier", "search_str"),
    ("cpp:identifier", "basis_vector_t"),
    ("cpp:identifier", "matrix_2x2_t"),
    ("cpp:identifier", "patt_color_rgb_t"),
    # Project macros (defined in headers)
    ("cpp:identifier", "STRSZ"),
    ("cpp:identifier", "STRSIZE"),
    ("cpp:identifier", "MAX_INPUT_FILES"),
    ("cpp:identifier", "PATH_MAX"),
    ("cpp:identifier", "NUM_COLORS"),
    ("cpp:identifier", "NUM_GRAYS"),
    ("cpp:identifier", "NUM_SUBS"),
    ("cpp:identifier", "INP_MAX"),
    ("cpp:identifier", "VAR_MAX"),
    ("cpp:identifier", "VFF_DEP_IEEEORDER"),
    ("cpp:identifier", "VFF_DEP_NSORDER"),
    ("cpp:identifier", "VFF_DEP_DECORDER"),
]

# Use regex patterns for common patterns (catches more variations)
nitpick_ignore_regex = [
    # Ignore all doxygen group/file references (often not fully resolved)
    (r"ref\.ref", r"group__.*"),
    (r"ref\.ref", r".*_8[ch].*"),
    (r"ref\.ref", r"lattice_8h.*"),
    # Ignore Doxygen struct/type references
    (r"ref\.ref", r"struct.*"),
    # Ignore document references to manual chapters not yet created
    (r"ref\.doc", r"ch\d+.*"),
    (r"ref\.doc", r"\.\./part-\d+/ch\d+.*"),
]


# -- Suppress warnings for missing Doxygen XML ----------------------------
# This allows building docs even when Doxygen hasn't been run

def setup(app):
    """Emit warning when Doxygen XML is not available."""
    import os
    import logging
    
    logger = logging.getLogger(__name__)
    doxygen_xml_path = os.path.join(os.path.dirname(__file__), '_build/doxygen/xml')
    index_xml = os.path.join(doxygen_xml_path, 'index.xml')
    
    if not os.path.exists(index_xml):
        logger.warning(
            "Doxygen XML not found at '%s'. "
            "API documentation will be incomplete. "
            "Run 'doxygen doxyfile.conf' in the doc/ directory to generate it.",
            doxygen_xml_path
        )
        # Create minimal placeholder to prevent Breathe from failing completely
        os.makedirs(doxygen_xml_path, exist_ok=True)
        with open(index_xml, 'w') as f:
            f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
            f.write('<!-- Placeholder: Doxygen XML not generated. Run doxygen first. -->\n')
            f.write('<doxygenindex></doxygenindex>\n')
