
/**
 * \file
 * \brief Master include file for the CLEED project.
 * \author Liam Deacon <liam.deacon@diamond.ac.uk>
 *
 * \mainpage
 *
 * \section intro Introduction
 *
 * This is an introduction.
 *
 * \section install Installation
 *
 * \subsection step1 Step 1: Pre-requisites
 *
 * etc...
 **/
 
#ifndef __CLEED_H__
#define __CLEED_H__

#include "leed.h"
#include "search.h"
#include "rfac.h"

#include "latt.h"
#include "patt.h"
#include "ftsmooth.h"

#endif /* __CLEED_H__ */